# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiparameters',
            name='lis_person_sourcedid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
