# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0003_auto_20160908_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiparameters',
            name='context_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ltiparameters',
            name='roles',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ltiparameters',
            name='custom_canvas_course_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ltiparameters',
            name='custom_canvas_user_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
