# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_engine_app', '0002_auto_20160427_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='result',
            new_name='value',
        ),
    ]
