# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaborator',
            unique_together=set([('user', 'course')]),
        ),
    ]
