# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_engine_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='component_id',
            new_name='component',
        ),
    ]
