# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='answer',
        ),
    ]
