# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoocletType',
        ),
    ]
