# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moocletversionvariablevalue',
            name='explanation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Explanation'),
        ),
    ]
