# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='context',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
