# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20160723_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='content_type',
        ),
        migrations.AddField(
            model_name='value',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
