# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_delete_mooclettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooclet',
            name='type',
            field=models.CharField(choices=[('explanation', 'explanation'), ('next_question', 'next_question')], default='explanation', max_length=100),
            preserve_default=False,
        ),
    ]
