# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engine', '0003_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizLtiParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lis_outcome_service_url', models.CharField(max_length=200)),
                ('lis_result_sourcedid', models.CharField(max_length=100)),
                ('consumer_key', models.CharField(max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
