# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('engine', '0003_auto_20160831_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooclettype',
            name='version_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_mooclet_type', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='mooclettype',
            name='parent_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_mooclet_type', to='contenttypes.ContentType'),
        ),
    ]
