# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20160831_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='mooclet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Mooclet'),
        ),
    ]
