# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_quizltiparameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizltiparameters',
            old_name='consumer_key',
            new_name='oauth_consumer_key',
        ),
        migrations.AlterUniqueTogether(
            name='quizltiparameters',
            unique_together=set([('user', 'quiz')]),
        ),
    ]
