# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20160725_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizltiparameters',
            name='lti_user_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quizltiparameters',
            name='lis_outcome_service_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizltiparameters',
            name='lis_result_sourcedid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quizltiparameters',
            name='oauth_consumer_key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
