# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20160901_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='mooclet_next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Mooclet'),
        ),
    ]
