# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20160725_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizltiparameters',
            options={'verbose_name': 'LTI Parameters', 'verbose_name_plural': 'LTI Parameters'},
        ),
        migrations.AddField(
            model_name='quizltiparameters',
            name='canvas_course_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quizltiparameters',
            name='canvas_user_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quizltiparameters',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quizltiparameters',
            name='lis_person_sourcedid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
