# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20160524_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
