# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_question_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='url',
        ),
    ]
