# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_auto_20160609_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuservariable',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='text',
            field=models.TextField(verbose_name='explanation text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='question text'),
        ),
    ]
