# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_auto_20160609_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='', max_length=100)),
                ('instance', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseuser',
            name='context',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='user_lms_id',
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='default_name', max_length=100, verbose_name='question name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='answer text'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engine.Course'),
            preserve_default=False,
        ),
    ]
